### ISSUE TITLE
[Bug]Unable to Display m3u8 Source on Win11

### ISSUE THREAD

**Issue by ZhiFengCode** [mindstorm38/fabric-webstream#25]
**Issue Description:**
I'm currently using version 1.2.3 and have successfully installed FFmpeg on a Windows 11. However, I'm encountering an issue where I'm unable to display m3u8 sources. When attempting to utilize this version, the screen only displays the inputted link and a black background, rather than the content of the m3u8 source.

**Steps to Reproduce:**
1. Install and run version 1.2.3 on a Windows 11.
2. Attempt to load m3u8 sources.

![image](https://github.com/mindstorm38/fabric-webstreamer/assets/99059155/84de6eb0-e7ea-417e-9ef5-33eac968910f)

**Comment by theorzr** [comment]
Do you see anything in game's logs?

**Comment by ZhiFengCode** [comment]
Sorry about that, I forgot to provide you with the logs. Upon reviewing the logs, it seems that there were issues with the content requests. Here's the content of the logs:

```
[17:55:32] [Render thread/ERROR]: [DisplayLayerHls:489F778A] Failed to request playlist, setting interval to 5 seconds.
java.io.IOException: HTTP request failed, status code: 404
	at fr.theorozier.webstreamer.display.render.DisplayLayerHls.requestPlaylistBlocking(DisplayLayerHls.java:183) ~[webstreamer-1.2.3.jar:?]
	at fr.theorozier.webstreamer.util.AsyncProcessor.lambda$fetch$0(AsyncProcessor.java:75) ~[webstreamer-1.2.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:55:34] [Render thread/ERROR]: [DisplayLayerHls:489F778A] Failed to request playlist, setting interval to 5 seconds.
java.io.IOException: HTTP request failed, status code: 404
	at fr.theorozier.webstreamer.display.render.DisplayLayerHls.requestPlaylistBlocking(DisplayLayerHls.java:183) ~[webstreamer-1.2.3.jar:?]
	at fr.theorozier.webstreamer.util.AsyncProcessor.lambda$fetch$0(AsyncProcessor.java:75) ~[webstreamer-1.2.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:55:34] [Render thread/INFO]: [-1621/80/35] Allocated a new display url 1#http://demo.m3u8play.com/m3u8/out/demo.m3u8.
[17:55:34] [Render thread/INFO]: [-1621/80/35] Allocated a new display url 1#http://demo.m3u8play.com/m3u8/out/demo.m3u8.
[17:55:34] [Render thread/INFO]: [-1621/80/35] Allocated a new display url 1#http://demo.m3u8play.com/m3u8/out/demo.m3u8.
[17:55:34] [Render thread/INFO]: [-1621/80/35] Allocated a new display url 1#http://demo.m3u8play.com/m3u8/out/demo.m3u8.
[17:55:34] [Render thread/INFO]: [-1621/80/35] Allocated a new display url 1#http://demo.m3u8play.com/m3u8/out/demo.m3u8.
[17:55:34] [Render thread/INFO]: [-1621/80/35] Allocated a new display url 1#http://demo.m3u8play.com/m3u8/out/demo.m3u8.
[17:55:34] [Render thread/INFO]: [-1621/80/35] Allocated a new display url 1#http://demo.m3u8play.com/m3u8/out/demo.m3u8.
```

Based on these logs, it appears that there were connectivity issues or the requested content was not available. We may need to investigate further to resolve the issue.

**Comment by ZhiFengCode** [comment]
Apologies for the inconvenience. Despite the logs indicating connection failures and content not found errors, you've confirmed that the links are indeed valid and you've tested multiple links successfully. This suggests that there might be another issue at play. We'll need to conduct further investigation to pinpoint the exact cause of the problem.

**Comment by ZhiFengCode** [comment]
Thank you for providing additional information. Based on the screenshot from Postman showing the 404 status, it's evident that the resource is indeed returning a not found status. It's possible that the m3u8 resource might be treated as a file rather than a supported content type by the mod. Setting up an Nginx server for testing might be a viable solution to confirm this hypothesis. Once tested, we can better understand if the issue lies with the content type handling.

![image](https://github.com/mindstorm38/fabric-webstreamer/assets/99059155/d3e25ab4-b33c-4a33-a159-8d2fd6ded954)

**Comment by mindstorm38** [comment]
Am I reading ChatGPT literally answering your own questions

**Comment by theorzr** [comment]
I don't understand this conversation (sorry if you're not english native) but anyway yes if the error code returned is 404, then it means that the problem doesn't come from the mod itself.
